RFC: Finalize website
HackLahSG/website pull request #3
Opened 2022-12-28 14:05 UTC by provsalt

This PR is a **RFC: Requesting for comment**. Please leave your feedback about how the code can be tidied out for production!

TODO:
- [x] Landing page
- [x] Register page 
- [ ] Code cleanup
- [ ] Code refactor

2022-12-29 01:23 UTC, cytronicoder requested changes
Looks fine so far - thanks a lot!

2022-12-29 01:23 UTC, cytronicoder commented on pages/index.tsx
> +				<meta name="description" content="HackLah! is a hackathon hosted for teenagers in Singapore. Join us in person on 18th March 2023 for fun, workshops, and hacking with like-minded individuals!"/>
We should change the `meta` description to be in sync with the Instagram account: *HackLah! is a hackathon hosted for teenagers in Singapore. Join us in person on 18th March 2023 for games, workshops, and hacking! 🇸🇬*

2022-12-29 06:56 UTC, provsalt commented on pages/index.tsx
> +				<meta name="description" content="HackLah! is a hackathon hosted for teenagers in Singapore. Join us in person on 18th March 2023 for fun, workshops, and hacking with like-minded individuals!"/>
fixed

2022-12-29 12:53 UTC, cytronicoder commented
@provsalt having technical issues right now - imagine not having access

2022-12-30 02:37 UTC, cytronicoder commented
I'll take over from here 🚀

2022-12-30 02:38 UTC, cytronicoder approved these changes
LGTM! Next step would be heavy CSS reformatting + mobile optimisation.

2022-12-30 03:57 UTC, provsalt reviewed
was this meant to be here?

2022-12-30 03:57 UTC, provsalt commented on components/about/about.tsx
> +				something new.{" "}
```suggestion
				something new.
```

2022-12-30 04:00 UTC, cytronicoder commented on components/about/about.tsx
> +				something new.{" "}
Hmm someone put a space character there 🤨

2022-12-30 04:01 UTC, cytronicoder commented on components/about/about.tsx
> +				something new.{" "}
Fixed!

2022-12-31 05:08 UTC, cytronicoder approved these changes
LGTM! Ship it 🚀

2022-12-31 05:09 UTC, merged